export { default as FancyTitle } from './FancyTitle'
export { default as Layout, ScrollContainerRefContext } from './Layout'
export { default as NavBar } from './NavBar'

export { default as TransitionSeries, genDelays } from './TransitionSeries'

export { default as Section } from './sections/Section'
export { default as Title } from './sections/Title'
export { default as About } from './sections/About'
export { default as Projects } from './sections/Projects'
export { default as Contact } from './sections/Contact'
export { default as Head } from './Head'
export { default as Footer } from './Footer'
export { default as Indicator } from './Indicator'
export { default as Button } from './Button'
export { default as QR } from './qr'
